//Just a simple sorting usage. Create a function that returns the elements of the input-array in a sorted manner.

public static class SortArray {
	public static Object[] sortArray(Object[] names) {Arrays.sort(names);return names;}
        public static int[] sortArray(int[] names){ Arrays.sort(names);return names;}
        public static long[] sortArray(long[] names){Arrays.sort(names); return names;}
        public static float[] sortArray(float[] names){Arrays.sort(names);return names;}
        public static double[] sortArray(double[] names){Arrays.sort(names);return names;}
}